=== mynameisi/_practice_SQL/src/properties.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for properties -->
<!ELEMENT properties ( comment?, entry* ) >
<!ATTLIST properties version CDATA #FIXED "1.0">
<!ELEMENT comment (#PCDATA) >
<!ELEMENT entry (#PCDATA) >
<!ATTLIST entry key CDATA #REQUIRED>


<!--If you're not into reading XML DTDs, this essentially says that 
wrapped within an outer <properties> tag is a <comment> tag, followed 
by any number of <entry> tags. For each <entry> tag, there is a key,e.g.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>Hi</comment>
<entry key="foo">bar</entry>
<entry key="fu">baz</entry>
</properties>

-->

=== mynameisi/_practice_SQL/src/helper/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<comment>This contains the properties of the project</comment>
	<entry key="DEBUG_MSG">false</entry><!-- 是否显示项目中的打印Debug打印语句 -->
	<entry key="USER_MSG">true</entry>

	<entry key="CHAR_ENCODING">UTF-8</entry><!-- 默认字符集编码 -->

	<entry key="DB_NOW">HSQLDB</entry><!-- 当前使用的数据库 -->

	<!-- MYSQL数据库相关配置 -->
	<entry key="MYSQL_DRIVER">com.mysql.jdbc.Driver</entry>
	<entry key="MYSQL_URL">jdbc:mysql://localhost:3306/test</entry>
	<entry key="MYSQL_USER">root</entry>
	<entry key="MYSQL_PASS"></entry>

	<!-- ORACLE数据库相关配置 -->
	<entry key="ORACLE_DRIVER">oracle.jdbc.OracleDriver</entry>
	<entry key="ORACLE_URL">jdbc:oracle:thin:hr/hr@localhost:1521/XE</entry>
	<entry key="ORACLE_USER">root</entry>
	<entry key="ORACLE_PASS"></entry>
	
	<!-- HSQLDB数据库相关配置 -->
	<entry key="HSQLDB_DRIVER">org.hsqldb.jdbcDriver</entry>
	<entry key="HSQLDB_URL">jdbc:hsqldb:file:./opt/db/testdb;shutdown=true</entry>
	<entry key="HSQLDB_USER">sa</entry>
	<entry key="HSQLDB_PASS"></entry>

	<!-- SQL答案 -->
	<entry key="sql0">select name from customer</entry>
	<entry key="sql1">select city from customer where name = 'Bill Smith'</entry>
	<entry key="sql2">select address,city,state from customer where name =
		'Bob Smith'</entry>
	<entry key="sql3">select name, city, zip from customer where name like
		'%Bill%'</entry>
	<entry key="sql4">select item_id from sale where price&lt;20</entry>
	<entry key="sql5">select item_id, price, quantity  from sale where
		price&gt;20 and quantity&gt;11</entry>
	<entry key="sql6">select item_id, price, quantity  from sale where price
		in (29.95, 19,95, 9.99)</entry>

</properties>

=== mynameisi/_practice_SQL/src/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
	<comment>This contains the properties of the project</comment>


	<entry key="INTERVAL_JUNIT">0</entry><!-- 每一个Junit测试运行1秒 -->
	<entry key="INTERVAL_DBSHUTDOWN">500</entry>

	<entry key="REDIRECT">false</entry>
	<entry key="STDOUT">stdout.txt</entry>
	<entry key="STDERR">stderr.txt</entry>


	<entry key="DEBUG_MSG">false</entry><!-- 是否显示项目中的打印Debug打印语句 -->
	<entry key="USER_MSG">true</entry>

	<entry key="DB_FRAMEWORK">NOPOOL</entry><!-- NOPOOL, DBCP, BONECP -->
	<entry key="DB_NOW">HSQLDB</entry><!-- HSQLDB,HSQLDB_IN_MEM, MYSQL, ORACLE -->

	<!-- MYSQL数据库相关配置 -->
	<entry key="MYSQL_DRIVER">com.mysql.jdbc.Driver</entry>
	<entry key="MYSQL_URL">jdbc:mysql://localhost:3306/test</entry>
	<entry key="MYSQL_USER">root</entry>
	<entry key="MYSQL_PASS"></entry>
	<entry key="HSQLDB_CLEANUP"></entry>

	<!-- ORACLE数据库相关配置 -->
	<entry key="ORACLE_DRIVER">oracle.jdbc.OracleDriver</entry>
	<entry key="ORACLE_URL">jdbc:oracle:thin:hr/hr@localhost:1521/XE</entry>
	<entry key="ORACLE_USER">root</entry>
	<entry key="ORACLE_PASS"></entry>
	<entry key="HSQLDB_CLEANUP"></entry>

	<!-- HSQLDB数据库相关配置 -->
	<entry key="HSQLDB_DRIVER">org.hsqldb.jdbcDriver</entry>
	<entry key="HSQLDB_URL">jdbc:hsqldb:file:./opt/db/testdb;shutdown=true</entry>
	<entry key="HSQLDB_USER">sa</entry>
	<entry key="HSQLDB_PASS"></entry>
	<entry key="HSQLDB_CLEANUP">SHUTDOWN</entry>
	
	<!-- HSQLDB_IN_MEM 数据库相关配置 -->
	<entry key="HSQLDB_IN_MEM_DRIVER">org.hsqldb.jdbcDriver</entry>
	<!-- make sure not to auto shutdown DB with in mem db, otherwise with nopool framework won't work -->
	<entry key="HSQLDB_IN_MEM_URL">jdbc:hsqldb:mem:testdb</entry> 
	<entry key="HSQLDB_IN_MEM_USER">sa</entry>
	<entry key="HSQLDB_IN_MEM_PASS"></entry>
	<entry key="HSQLDB_CLEANUP">SHUTDOWN</entry>


</properties>
